languageCode = "en-us"
title = "Orbis Mobile's Blog"
pygmentsUseClasses= true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle =  "monokai"
pygmentsUseClasses = true

[taxonomies]
  tag = "tags"
  category = "categories"
